server:
  port: 8099
  servlet:
    context-path: /

spring:
  application:
    name: AgentTest
  profiles:
    active: local

langchain4j:
  community:
    dashscope:
      chat-model:
        api-key: <You API Key here>
        model-name: qwen-plus
        temperature: 0.7
        max-tokens: 4096
        top-p: 0.9
        stream: true

logging:
  level:
    com.alibaba.dashscope: DEBUG  # 查看 DashScope SDK 的请求细节
    dev.langchain4j: DEBUG